# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.TextField(help_text='Comentario', verbose_name='Comentario')),
                ('fecha_comentario', models.DateTimeField(auto_now=True, verbose_name='Fecha del Comentario')),
                ('usuario_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_video', models.CharField(help_text='Titulo ', max_length=100, verbose_name='Titulo ')),
                ('descripcion_video', models.TextField(help_text='Descripcion ', verbose_name='Descripcion ')),
                ('keywords_video', models.TextField(help_text='Palabras de referencia', verbose_name='Palabras de referencia')),
                ('archivo_video', models.FileField(help_text='Seleccione un archivo', upload_to='videos', verbose_name='Seleccione un archivo')),
                ('fecha_video', models.DateTimeField(auto_now=True)),
                ('privacidad_video', models.BooleanField(default=False, help_text='Privado', verbose_name='Privado')),
                ('usuario_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario ')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='video_comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
    ]
