# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='archivo_video',
            field=models.FileField(help_text='Seleccione un archivo', upload_to='/media/videos', verbose_name='Seleccione un archivo'),
        ),
    ]
