# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170103_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='archivo_video',
            field=models.FileField(help_text='Seleccione un archivo', upload_to='videos', verbose_name='Seleccione un archivo'),
        ),
    ]
